### ISSUE TITLE
php-ds/polyfill

### ISSUE THREAD

**Issue by dmonllao** [SciPHPy/php-sds-polyfill#45]
Hi @castarco, this is an interesting project. I'm looking for a good data structures library for php-ml neural nets implementation. Would it be an option to switch PHP native arrays to php-ds types requiring https://github.com/php-ds/polyfill (not used if the extension is installed according to the project docs)

**Comment by castarco** [comment]
Hi, @dmonllao .

I'm afraid that this idea isn't a good choice. In fact, I did some experiments, and the results weren't good¹. What we should do is to port this polyfill to a native extension, as php-ds, but with other structures.

1. https://blog.coderspirit.xyz/blog/2016/12/16/naive-matrix-multiplication-benchmark-php/
